#!/bin/bash

# Function to create the new day directory and setup files.
setup_new_day() {
	local day=$1
	local base_dir="../"
	local new_day_dir="${base_dir}day${day}"

	# Check if the directory already exists
	if [ -d "$new_day_dir" ]; then
		echo "Directory $new_day_dir already exists. Please choose a different day."
		exit 1
	fi

	# Create the directory
	mkdir "$new_day_dir"
	cd "$new_day_dir" || exit

	# Create README.md
	local readme="Day: $day\\n
	\\n
	## Part 1\\n
	<Insert details from Advent of Code webpage>\\n
	\\n
	## Part 2
	<Insert details from Advent of Code webpage>\\n
	\\n
	"
	echo $readme > README.md

	# Create python script
	echo "Creating Python scipts for Part 1 and Part 2"
	touch part1.py
	touch part2.py

	# Download the real puzzle input
	local input_url="https://adventofcode.com/2024/day/${day}/input"
	echo "Downloading real puzzle from: ${input_url}"
	curl -o real_input.txt -c "${SESSION_COOKIE}" "${input_url}"

	echo "Setup complete for Day ${day}"
}

# Check if a day number is provided
if [ -z "$1" ]; then
	echo "Usage: ./new_day <day_number>"
fi

setup_new_day "$1"
