#!/bin/bash

# Function to create the new day directory and setup files.
setup_new_day() {
	local day=$1
	local base_dir="../2024/"
	local new_day_dir="${base_dir}day${day}"

	# Check if the directory already exists
	if [ -d "$new_day_dir" ]; then
		echo "Directory $new_day_dir already exists. Please choose a different day."
		exit 1
	fi

	# Create the directory
	mkdir "$new_day_dir"
	cd "$new_day_dir" || exit

	# Create README.md
	echo "Fetching details for Day $day form Avent of Code..."
	local output=$(../../scripts/create_readme "$day")
	local title=$(echo "$output" | awk -F 'Title: ' '/Title: /{getline; print}')
	local body=$(echo "$output" | awk -F 'Body: ' '/Body:/{getline; print}')
	echo -e "# ${title}\n\n${body}\n" > README.md
	echo "README.md created with fetched details."

	# Create python script
	echo "Creating Python scipts for Part 1 and Part 2"
	touch part1.py
	touch part2.py

	# Download the real puzzle input
	local input_url="https://adventofcode.com/2024/day/${day}/input"
	echo "Downloading real puzzle from: ${input_url}"
	echo "SESSION_COOKIE=${SESSION_COOKIE}"
	curl -so real_input.txt --cookie "${SESSION_COOKIE}" "${input_url}"

	echo "Setup complete for Day ${day}"
}

# Check if a day number is provided
if [ -z "$1" ]; then
	echo "Usage: ./new_day <day_number>"
	exit 1
fi

setup_new_day "$1"
